# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\salil\Desktop/SpeechRecognition.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1380, 800)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(3600, 2400))
        MainWindow.setFocusPolicy(QtCore.Qt.ClickFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/micro.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.460227, y2:0.635, stop:0.0738636 rgba(44, 89, 134, 255), stop:1 rgba(0, 170, 255, 255));\n"
""))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1391, 61))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frame_2 = QtGui.QFrame(self.verticalLayoutWidget)
        self.frame_2.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:0.995, y2:1, stop:0.698864 rgba(0, 58, 85, 255), stop:0.846591 rgba(0, 68, 100, 255));"))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.Tab = QtGui.QTabWidget(self.frame_2)
        self.Tab.setGeometry(QtCore.QRect(0, 20, 1381, 521))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Tab.setFont(font)
        self.Tab.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.Tab.setObjectName(_fromUtf8("Tab"))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.Tab.addTab(self.tab_2, _fromUtf8(""))
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtGui.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(0, 560, 2011, 101))
        self.frame_3.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:0.722, y2:0.629, stop:0.698864 rgba(58, 58, 58, 255), stop:0.846591 rgba(17, 17, 17, 255));"))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.frame = QtGui.QFrame(self.frame_3)
        self.frame.setGeometry(QtCore.QRect(370, 10, 691, 80))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.stackedWidget = QtGui.QStackedWidget(self.frame)
        self.stackedWidget.setGeometry(QtCore.QRect(460, 0, 121, 80))
        self.stackedWidget.setStyleSheet(_fromUtf8("\n"
"background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:1, stop:0.0738636 rgba(0, 0, 0, 255), stop:1 rgba(118, 118, 118, 255));"))
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.toolButton_3 = QtGui.QToolButton(self.page)
        self.toolButton_3.setGeometry(QtCore.QRect(-10, 0, 101, 80))
        self.toolButton_3.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/mail.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_3.setIcon(icon1)
        self.toolButton_3.setIconSize(QtCore.QSize(120, 80))
        self.toolButton_3.setAutoRaise(True)
        self.toolButton_3.setObjectName(_fromUtf8("toolButton_3"))
        self.stackedWidget.addWidget(self.page)
        self.page_13 = QtGui.QWidget()
        self.page_13.setObjectName(_fromUtf8("page_13"))
        self.toolButton_6 = QtGui.QToolButton(self.page_13)
        self.toolButton_6.setGeometry(QtCore.QRect(-40, 0, 161, 80))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/fb.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_6.setIcon(icon2)
        self.toolButton_6.setIconSize(QtCore.QSize(91, 80))
        self.toolButton_6.setObjectName(_fromUtf8("toolButton_6"))
        self.stackedWidget.addWidget(self.page_13)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.toolButton_4 = QtGui.QToolButton(self.page_2)
        self.toolButton_4.setGeometry(QtCore.QRect(0, 0, 81, 80))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/chrome.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_4.setIcon(icon3)
        self.toolButton_4.setIconSize(QtCore.QSize(120, 80))
        self.toolButton_4.setObjectName(_fromUtf8("toolButton_4"))
        self.stackedWidget.addWidget(self.page_2)
        self.stackedWidget_2 = QtGui.QStackedWidget(self.frame)
        self.stackedWidget_2.setGeometry(QtCore.QRect(340, 0, 121, 80))
        self.stackedWidget_2.setStyleSheet(_fromUtf8(""))
        self.stackedWidget_2.setObjectName(_fromUtf8("stackedWidget_2"))
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.toolButton_2 = QtGui.QToolButton(self.page_3)
        self.toolButton_2.setGeometry(QtCore.QRect(0, 0, 91, 80))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/nowifi.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon4)
        self.toolButton_2.setIconSize(QtCore.QSize(91, 80))
        self.toolButton_2.setObjectName(_fromUtf8("toolButton_2"))
        self.stackedWidget_2.addWidget(self.page_3)
        self.page_4 = QtGui.QWidget()
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.toolButton_5 = QtGui.QToolButton(self.page_4)
        self.toolButton_5.setGeometry(QtCore.QRect(0, 0, 81, 80))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/wifion.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_5.setIcon(icon5)
        self.toolButton_5.setIconSize(QtCore.QSize(100, 80))
        self.toolButton_5.setObjectName(_fromUtf8("toolButton_5"))
        self.stackedWidget_2.addWidget(self.page_4)
        self.stackedWidget_3 = QtGui.QStackedWidget(self.frame)
        self.stackedWidget_3.setGeometry(QtCore.QRect(230, 0, 111, 80))
        self.stackedWidget_3.setStyleSheet(_fromUtf8(""))
        self.stackedWidget_3.setObjectName(_fromUtf8("stackedWidget_3"))
        self.page_5 = QtGui.QWidget()
        self.page_5.setObjectName(_fromUtf8("page_5"))
        self.toolButton_7 = QtGui.QToolButton(self.page_5)
        self.toolButton_7.setGeometry(QtCore.QRect(0, 0, 81, 81))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/blueno.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_7.setIcon(icon6)
        self.toolButton_7.setIconSize(QtCore.QSize(120, 80))
        self.toolButton_7.setObjectName(_fromUtf8("toolButton_7"))
        self.stackedWidget_3.addWidget(self.page_5)
        self.page_6 = QtGui.QWidget()
        self.page_6.setObjectName(_fromUtf8("page_6"))
        self.toolButton_8 = QtGui.QToolButton(self.page_6)
        self.toolButton_8.setGeometry(QtCore.QRect(0, 0, 81, 80))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/blueon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_8.setIcon(icon7)
        self.toolButton_8.setIconSize(QtCore.QSize(120, 80))
        self.toolButton_8.setObjectName(_fromUtf8("toolButton_8"))
        self.stackedWidget_3.addWidget(self.page_6)
        self.stackedWidget_6 = QtGui.QStackedWidget(self.frame)
        self.stackedWidget_6.setGeometry(QtCore.QRect(0, 0, 121, 80))
        self.stackedWidget_6.setStyleSheet(_fromUtf8(""))
        self.stackedWidget_6.setObjectName(_fromUtf8("stackedWidget_6"))
        self.page_11 = QtGui.QWidget()
        self.page_11.setObjectName(_fromUtf8("page_11"))
        self.toolButton_13 = QtGui.QToolButton(self.page_11)
        self.toolButton_13.setGeometry(QtCore.QRect(0, 0, 81, 80))
        self.toolButton_13.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/acceptcall.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_13.setIcon(icon8)
        self.toolButton_13.setIconSize(QtCore.QSize(120, 80))
        self.toolButton_13.setObjectName(_fromUtf8("toolButton_13"))
        self.stackedWidget_6.addWidget(self.page_11)
        self.page_12 = QtGui.QWidget()
        self.page_12.setObjectName(_fromUtf8("page_12"))
        self.toolButton_14 = QtGui.QToolButton(self.page_12)
        self.toolButton_14.setGeometry(QtCore.QRect(0, 0, 81, 80))
        self.toolButton_14.setStyleSheet(_fromUtf8("image: url(:/icons/call.png);"))
        self.toolButton_14.setText(_fromUtf8(""))
        self.toolButton_14.setIconSize(QtCore.QSize(120, 80))
        self.toolButton_14.setObjectName(_fromUtf8("toolButton_14"))
        self.stackedWidget_6.addWidget(self.page_12)
        self.stackedWidget_5 = QtGui.QStackedWidget(self.frame)
        self.stackedWidget_5.setGeometry(QtCore.QRect(120, 0, 111, 80))
        self.stackedWidget_5.setStyleSheet(_fromUtf8(""))
        self.stackedWidget_5.setObjectName(_fromUtf8("stackedWidget_5"))
        self.page_9 = QtGui.QWidget()
        self.page_9.setObjectName(_fromUtf8("page_9"))
        self.toolButton_11 = QtGui.QToolButton(self.page_9)
        self.toolButton_11.setGeometry(QtCore.QRect(0, 0, 81, 80))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/pause.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_11.setIcon(icon9)
        self.toolButton_11.setIconSize(QtCore.QSize(120, 80))
        self.toolButton_11.setObjectName(_fromUtf8("toolButton_11"))
        self.stackedWidget_5.addWidget(self.page_9)
        self.page_10 = QtGui.QWidget()
        self.page_10.setObjectName(_fromUtf8("page_10"))
        self.toolButton_12 = QtGui.QToolButton(self.page_10)
        self.toolButton_12.setGeometry(QtCore.QRect(0, 0, 81, 80))
        self.toolButton_12.setText(_fromUtf8(""))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/play.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_12.setIcon(icon10)
        self.toolButton_12.setIconSize(QtCore.QSize(91, 80))
        self.toolButton_12.setObjectName(_fromUtf8("toolButton_12"))
        self.stackedWidget_5.addWidget(self.page_10)
        self.stackedWidget_4 = QtGui.QStackedWidget(self.frame)
        self.stackedWidget_4.setGeometry(QtCore.QRect(580, 0, 111, 80))
        self.stackedWidget_4.setStyleSheet(_fromUtf8(""))
        self.stackedWidget_4.setObjectName(_fromUtf8("stackedWidget_4"))
        self.page_15 = QtGui.QWidget()
        self.page_15.setObjectName(_fromUtf8("page_15"))
        self.toolButton_16 = QtGui.QToolButton(self.page_15)
        self.toolButton_16.setGeometry(QtCore.QRect(-40, 0, 161, 81))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/hospital.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_16.setIcon(icon11)
        self.toolButton_16.setIconSize(QtCore.QSize(91, 80))
        self.toolButton_16.setObjectName(_fromUtf8("toolButton_16"))
        self.stackedWidget_4.addWidget(self.page_15)
        self.page_7 = QtGui.QWidget()
        self.page_7.setObjectName(_fromUtf8("page_7"))
        self.toolButton_9 = QtGui.QToolButton(self.page_7)
        self.toolButton_9.setGeometry(QtCore.QRect(-30, 0, 141, 80))
        self.toolButton_9.setText(_fromUtf8(""))
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/gas.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_9.setIcon(icon12)
        self.toolButton_9.setIconSize(QtCore.QSize(91, 80))
        self.toolButton_9.setObjectName(_fromUtf8("toolButton_9"))
        self.stackedWidget_4.addWidget(self.page_7)
        self.page_14 = QtGui.QWidget()
        self.page_14.setObjectName(_fromUtf8("page_14"))
        self.toolButton_15 = QtGui.QToolButton(self.page_14)
        self.toolButton_15.setGeometry(QtCore.QRect(-30, 0, 141, 80))
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/eatery.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_15.setIcon(icon13)
        self.toolButton_15.setIconSize(QtCore.QSize(91, 80))
        self.toolButton_15.setObjectName(_fromUtf8("toolButton_15"))
        self.stackedWidget_4.addWidget(self.page_14)
        self.page_16 = QtGui.QWidget()
        self.page_16.setObjectName(_fromUtf8("page_16"))
        self.toolButton_17 = QtGui.QToolButton(self.page_16)
        self.toolButton_17.setGeometry(QtCore.QRect(-40, 0, 151, 81))
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/home.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_17.setIcon(icon14)
        self.toolButton_17.setIconSize(QtCore.QSize(91, 80))
        self.toolButton_17.setCheckable(True)
        self.toolButton_17.setObjectName(_fromUtf8("toolButton_17"))
        self.stackedWidget_4.addWidget(self.page_16)
        self.page_8 = QtGui.QWidget()
        self.page_8.setObjectName(_fromUtf8("page_8"))
        self.toolButton_10 = QtGui.QToolButton(self.page_8)
        self.toolButton_10.setGeometry(QtCore.QRect(0, 0, 81, 80))
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/directions.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_10.setIcon(icon15)
        self.toolButton_10.setIconSize(QtCore.QSize(120, 80))
        self.toolButton_10.setObjectName(_fromUtf8("toolButton_10"))
        self.stackedWidget_4.addWidget(self.page_8)
        self.SpeakBtn = QtGui.QPushButton(self.centralwidget)
        self.SpeakBtn.setGeometry(QtCore.QRect(620, 220, 103, 88))
        self.SpeakBtn.setText(_fromUtf8(""))
        self.SpeakBtn.setIcon(icon)
        self.SpeakBtn.setIconSize(QtCore.QSize(91, 80))
        self.SpeakBtn.setCheckable(True)
        self.SpeakBtn.setObjectName(_fromUtf8("SpeakBtn"))
        self.listWidget = QtGui.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(0, 60, 231, 501))
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.verticalSlider = QtGui.QSlider(self.centralwidget)
        self.verticalSlider.setGeometry(QtCore.QRect(90, 150, 61, 391))
        self.verticalSlider.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:0.995, y2:1, stop:0.698864 rgba(0, 58, 85, 255), stop:0.846591 rgba(0, 68, 100, 255));"))
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName(_fromUtf8("verticalSlider"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1380, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.Tab.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(0)
        self.stackedWidget_3.setCurrentIndex(0)
        self.stackedWidget_6.setCurrentIndex(0)
        self.stackedWidget_5.setCurrentIndex(0)
        self.stackedWidget_4.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "SpeechRecognitionSystemTeam9", None))
        self.Tab.setTabText(self.Tab.indexOf(self.tab_2), _translate("MainWindow", "Home", None))
        self.toolButton_6.setText(_translate("MainWindow", "...", None))
        self.toolButton_4.setText(_translate("MainWindow", "1", None))
        self.toolButton_2.setText(_translate("MainWindow", "...", None))
        self.toolButton_5.setText(_translate("MainWindow", "...", None))
        self.toolButton_7.setText(_translate("MainWindow", "2", None))
        self.toolButton_8.setText(_translate("MainWindow", "1", None))
        self.toolButton_11.setText(_translate("MainWindow", "2", None))
        self.toolButton_16.setText(_translate("MainWindow", "...", None))
        self.toolButton_15.setText(_translate("MainWindow", "...", None))
        self.toolButton_17.setText(_translate("MainWindow", "...", None))
        self.toolButton_10.setText(_translate("MainWindow", "1", None))

import icons_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

